name: 25-eva-hadox-dev

services:
  archive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 25-eva-hadox-archive-dev
    environment:
      PORT: 8080
      DATA_DIR: /app/runtime-data
    ports:
      - "4173:8080"
    volumes:
      - ./runtime-data:/app/runtime-data
    restart: unless-stopped
